kafka:
  bootstrap-servers: 192.168.0.26:9092
  topic:
    spring-integration-kafka: test.integration.spring
spring:
  jmx:
    enabled: false
server:
    port: 8081
inbound:
  read.path: /home/joset/data/
  out.path: /home/joset/data/out/
  filename:
    regex: ([^\\s]+(\\.(?i)(txt))$)
  file:
    poller-fixed-delay: 1000
    poller-max-messages-per-poll: 4
debug: true
logging:
  file: /home/joset/logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
